# Generated by Django 2.2 on 2019-07-27 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='photo',
        ),
        migrations.CreateModel(
            name='JobImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='job_photo')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job.Job')),
            ],
        ),
    ]
