# Generated by Django 2.2 on 2019-08-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20190727_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='job_photo'),
        ),
        migrations.DeleteModel(
            name='JobImage',
        ),
    ]
